trigger:
  branches:
    include:
      - main

stages:
- stage: BuildPush
  jobs:
  - job: DockerBuild
    steps:

    - script: 'docker --version'
      displayName: 'Docker Version'
    
    - script: 'docker login -u $(USERNAME) -p $(PASSWORD)'
      displayName: 'Docker Login'

    - script: 'docker build -t udaykiranthallapelli/welcome-image:1.3 -f Dockerfile .'
      displayName: 'Docker Build'

    - script: 'docker push udaykiranthallapelli/welcome-image:1.3'
      displayName: 'Docker Push'